### ISSUE TITLE
Strong named assemblies

### ISSUE THREAD

**Issue by KostaMadorsky** [twcclegg/libphonenumber-csharp#171] opened 2023-05-18 01:58 UTC
It would be great if you could publish signed assemblies in line with [Microsoft's guidance for open-source libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming#create-strong-named-net-libraries).

Here's the guide on [How to: Sign an assembly with a strong name](https://learn.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name).

Thanks! 🙂

**Comment by KostaMadorsky** [comment] 2023-05-18 02:14
This may cause binary breaking change...

**Comment by twcclegg** [comment] 2023-05-19 16:40
Duplicate of #53

**Closed as completed by twcclegg** 2023-05-19 16:40 UTC
