### ISSUE TITLE
Get Regions and CountryCode easily

### ISSUE THREAD

**Issue by pcdus** [twcclegg/libphonenumber-csharp#73] opened 2018-09-20 10:06 UTC
Hello,

We currently use the library to get country code for each available regions like this:

```
var uti = PhoneNumberUtil.GetInstance();
var regions = new ObservableCollection<CountryPhone>();
foreach (var region in uti.GetSupportedRegions())
{
    var val = uti.GetCountryCodeForRegion(region);
    regions.Add(new CountryPhone
    {
        // ...
    });
}
```

But this takes a long time the first time. 
Isn't there a way to get all the CountryCode for one shot?

**Comment by AwsomeCode** [comment] 2018-09-20 10:30
This is just port of https://github.com/googlei18n/libphonenumber 
Check or request over there.

**Comment by twcclegg** [comment] 2018-09-20 14:47
This sounds like a symptom of https://github.com/twcclegg/libphonenumber-csharp/issues/4 which is due to functionality missing in this port. There is work in progress here https://github.com/twcclegg/libphonenumber-csharp/pull/45.
As per just having a function just for this see @AwsomeCode 's comment above, also I would guess this hypothetical function would be just as slow on first use.

**Comment by twcclegg** [comment] 2018-09-21 06:45
Closing as duplicate of #4.

**Closed as completed by twcclegg** 2018-09-21 06:45 UTC
